services:
  server:
    entrypoint: bash -c "npm run build && npm run start:prod"
    ports:
      - 80:3000
    environment:
      CORS_ORIGIN: ${CORS_ORIGIN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

  db:
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
