services:
  server:
    entrypoint: bash -c "npm install && npm run start:debug"
  client:
    image: node:18
    volumes:
      - ./client:/workspace
    working_dir: /workspace
    entrypoint: bash -c "npm install && npm run dev"
    ports:
      - 5000:3000

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
