services:
  core:
    image: node:18
    volumes:
      - ./core:/workspace
    working_dir: /workspace
    entrypoint: bash -c "npm install && npm run run"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_CLIENT_ID: ${MAILER_CLIENT_ID}
      MAILER_CLIENT_PWD: ${MAILER_CLIENT_PWD}
      MAILER_REFTKN: ${MAILER_REFTKN}
    depends_on:
      db:
        condition: service_healthy

  server:
    image: node:18
    volumes:
      - ./server:/workspace
    working_dir: /workspace
    ports:
      - 3000:3000
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

  db:
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
